project:
  type: website
  output-dir: docs

website:
  title: "YONG GYU LEE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hw3.qmd
        text: hw3
      - href: hw4.qmd
        text: hw4
      - href: blog.qmd
        text: Blog


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

