project:
  type: website
  output-dir: docs

website:
  title: "YONG GYU LEE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: hw3.qmd
        text: hw3

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

